/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import KentHipos.Kensoft;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Cliente;
import modelo.Habitacion;
import modelo.Reservacion;
import sistemareserva.Main;

/**
 *
 * @author Usuario
 */
public class ClienteUI extends javax.swing.JFrame {

    private static final int MAX_PER_PAGE = 5;

    private Cliente clienteLogged;
    private List<Reservacion> reservaciones;
    private int reservacionespaginaActual = 0;
    private int reservacionesPaginasTotales;

    /**
     * Creates new form Inicial
     */
    public ClienteUI() {
        initComponents();
    }

    public ClienteUI(Cliente clienteLogged) {
        this.clienteLogged = clienteLogged;
        this.reservaciones = Main.reservaciones(clienteLogged.getDocumento());
        reservacionesPaginasTotales = reservaciones.size() / MAX_PER_PAGE;
        if (reservaciones.size() % MAX_PER_PAGE != 0) {
            reservacionesPaginasTotales++;
        }
        initComponents();
        loggedUserNameLabel.setText("Bienvenidx, " + clienteLogged.getNombre());
        cargarReservaciones();

        reservacionesPrevBtn.addActionListener(this::changeReservacionesPage);
        reservacionesNextBtn.addActionListener(this::changeReservacionesPage);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JPanel();
        logoImg = new javax.swing.JLabel();
        menuButton = new javax.swing.JLabel();
        loggedUserNameLabel = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        content = new javax.swing.JTabbedPane();
        main = new javax.swing.JPanel();
        mainReservacionesPagPanel = new javax.swing.JPanel();
        reservacionesPrevBtn = new javax.swing.JButton();
        reservacionesPagLabel = new javax.swing.JLabel();
        reservacionesNextBtn = new javax.swing.JButton();
        mainReservacionesPanel = new javax.swing.JPanel();
        mainBackground = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toolbar.setBackground(new java.awt.Color(0, 0, 0));
        toolbar.setMaximumSize(new java.awt.Dimension(910, 80));
        toolbar.setMinimumSize(new java.awt.Dimension(910, 80));

        logoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logonombre.png"))); // NOI18N

        menuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_menu.png"))); // NOI18N
        menuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuButtonMouseClicked(evt);
            }
        });

        loggedUserNameLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        loggedUserNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        loggedUserNameLabel.setText("Bienvenid@");

        javax.swing.GroupLayout toolbarLayout = new javax.swing.GroupLayout(toolbar);
        toolbar.setLayout(toolbarLayout);
        toolbarLayout.setHorizontalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(menuButton)
                .addGap(18, 18, 18)
                .addComponent(loggedUserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoImg)
                .addGap(56, 56, 56))
        );
        toolbarLayout.setVerticalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(logoImg))
            .addGroup(toolbarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loggedUserNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(toolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        menu.setBackground(new java.awt.Color(0, 0, 0, 220));
        menu.setMaximumSize(new java.awt.Dimension(180, 720));
        menu.setMinimumSize(new java.awt.Dimension(180, 720));
        menu.setPreferredSize(new java.awt.Dimension(180, 720));

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, 180, 720));

        content.setEnabled(false);
        content.setMaximumSize(new java.awt.Dimension(900, 680));
        content.setMinimumSize(new java.awt.Dimension(900, 680));
        content.setPreferredSize(new java.awt.Dimension(900, 680));

        main.setMaximumSize(new java.awt.Dimension(1080, 645));
        main.setMinimumSize(new java.awt.Dimension(1080, 645));
        main.setPreferredSize(new java.awt.Dimension(1080, 645));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainReservacionesPagPanel.setLayout(new java.awt.GridLayout(1, 3));

        reservacionesPrevBtn.setText("<");
        mainReservacionesPagPanel.add(reservacionesPrevBtn);

        reservacionesPagLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservacionesPagLabel.setText("Página (1/1)");
        mainReservacionesPagPanel.add(reservacionesPagLabel);

        reservacionesNextBtn.setText(">");
        mainReservacionesPagPanel.add(reservacionesNextBtn);

        main.add(mainReservacionesPagPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 590, 648, 30));

        mainReservacionesPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainReservacionesPanel.setLayout(new java.awt.GridLayout(5, 1));
        main.add(mainReservacionesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 64, 648, 516));

        mainBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicio.jpg"))); // NOI18N
        main.add(mainBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, -1, -1));

        content.addTab("tab1", main);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        content.addTab("tab2", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        content.addTab("tab3", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        content.addTab("tab4", jPanel3);

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1080, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuButtonMouseClicked

        Kensoft animate = new Kensoft();
        if (menu.getLocation().x == 0) {
            animate.jPanelXLeft(0, -180, 1, 1, menu);
        } else {
            animate.jPanelXRight(-180, 0, 1, 1, menu);
        }
    }//GEN-LAST:event_menuButtonMouseClicked

    private void cargarReservaciones() {
        mainReservacionesPanel.removeAll();
        mainReservacionesPanel.revalidate();
        mainReservacionesPanel.repaint();
        List<Reservacion> filtrados;
        if (reservaciones.size() <= MAX_PER_PAGE) {
            filtrados = reservaciones;

        } else {
            int inicio = reservacionespaginaActual * MAX_PER_PAGE;
            int fin = inicio + MAX_PER_PAGE;
            if (fin > reservaciones.size()) {
                fin = reservaciones.size();
            }
            filtrados = reservaciones.subList(inicio, fin);

        }
        for (Reservacion reservacion : filtrados) {
            mainReservacionesPanel.add(buildReservacionCard(reservacion));
        }
        int paginaActual = reservacionespaginaActual + 1;
        reservacionesPagLabel.setText("Página (" + paginaActual + "/" + reservacionesPaginasTotales + ")");
    }

    private javax.swing.JPanel buildReservacionCard(Reservacion reservacion) {
        Habitacion habitacion = reservacion.getHabitacion();
        javax.swing.JPanel reservacionCard = new javax.swing.JPanel();
        javax.swing.JLabel habitacionLabel = new javax.swing.JLabel();
        javax.swing.JLabel habitacionValue = new javax.swing.JLabel();
        javax.swing.JLabel precioNocheLabel = new javax.swing.JLabel();
        javax.swing.JLabel precioNocheValue = new javax.swing.JLabel();
        javax.swing.JLabel fechasLabel = new javax.swing.JLabel();
        javax.swing.JLabel fechasValue = new javax.swing.JLabel();
        javax.swing.JLabel estadoLabel = new javax.swing.JLabel();
        javax.swing.JLabel estadoValue = new javax.swing.JLabel();
        javax.swing.JLabel totalLabel = new javax.swing.JLabel();
        javax.swing.JLabel totalValue = new javax.swing.JLabel();

        reservacionCard.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        reservacionCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        habitacionLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        habitacionLabel.setText("Habitacion:");
        reservacionCard.add(habitacionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        habitacionValue.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        habitacionValue.setText("" + habitacion.getNumero() + " (" + habitacion.getTipo().name() + ")");
        reservacionCard.add(habitacionValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        precioNocheLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        precioNocheLabel.setText("Precio por noche:");
        reservacionCard.add(precioNocheLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        precioNocheValue.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        precioNocheValue.setText("$ " + habitacion.getPrecioPorNoche());
        reservacionCard.add(precioNocheValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        fechasLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        fechasLabel.setText("Fechas:");
        reservacionCard.add(fechasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        fechasValue.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        String inicio = df.format(reservacion.getFechaInicio());
        String fin = df.format(reservacion.getFechaFin());
        fechasValue.setText(inicio + " - " + fin + " (" + reservacion.getDias() + " noches)");
        reservacionCard.add(fechasValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        estadoLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        estadoLabel.setText("Estado de la reserva:");
        reservacionCard.add(estadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        estadoValue.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        estadoValue.setText(reservacion.getEstado().name());
        reservacionCard.add(estadoValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        totalLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        totalLabel.setText("Total pagado:");
        reservacionCard.add(totalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        totalValue.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        totalValue.setText("$ " + reservacion.getPago().getMonto() + " (" + reservacion.getPago().getTipo().name() + ")");
        reservacionCard.add(totalValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        return reservacionCard;
    }

    private void changeReservacionesPage(java.awt.event.ActionEvent evt) {
        if (evt.getActionCommand().equals(reservacionesNextBtn.getActionCommand())) {
            if (reservacionespaginaActual < reservacionesPaginasTotales - 1) {
                reservacionespaginaActual++;
                cargarReservaciones();
            }
        } else {
            if (reservacionespaginaActual > 0) {
                reservacionespaginaActual--;
                cargarReservaciones();
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane content;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel loggedUserNameLabel;
    private javax.swing.JLabel logoImg;
    private javax.swing.JPanel main;
    private javax.swing.JLabel mainBackground;
    private javax.swing.JPanel mainReservacionesPagPanel;
    private javax.swing.JPanel mainReservacionesPanel;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel menuButton;
    private javax.swing.JButton reservacionesNextBtn;
    private javax.swing.JLabel reservacionesPagLabel;
    private javax.swing.JButton reservacionesPrevBtn;
    private javax.swing.JPanel toolbar;
    // End of variables declaration//GEN-END:variables
}
