/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GUI.panel.HabitacionesPanel;
import KentHipos.Kensoft;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Habitacion;
import modelo.Reservacion;
import sistemareserva.Main;

/**
 *
 * @author Usuario
 */
public class ClienteUI extends javax.swing.JFrame {

    private static final int MAX_PER_PAGE = 5;

    private Cliente clienteLogged;
    private int reservacionespaginaActual = 0;
    private int reservacionesPaginasTotales;

    /**
     * Creates new form Inicial
     */
    public ClienteUI() {
        initComponents();
    }

    public ClienteUI(Cliente clienteLogged) {
        this.clienteLogged = clienteLogged;
        this.clienteLogged.setReservas(Main.reservaciones(clienteLogged.getDocumento()));
        reservacionesPaginasTotales = this.clienteLogged.getReservas().size() / MAX_PER_PAGE;
        if (this.clienteLogged.getReservas().size() % MAX_PER_PAGE != 0) {
            reservacionesPaginasTotales++;
        }
        initComponents();
        loadPerfil();

        contentHabitaciones = new HabitacionesPanel(this);
        contentHabitaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        reservasPanel.add(contentHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 640));

        loggedUserNameLabel.setText("Bienvenidx, " + clienteLogged.getNombre());
        cargarReservaciones();

        menuReservasBtn.addActionListener(this::changePanel);
        menuReservarBtn.addActionListener(this::changePanel);
        menuPerfilBtn.addActionListener(this::changePanel);

        reservacionesPrevBtn.addActionListener(this::changeReservacionesPage);
        reservacionesNextBtn.addActionListener(this::changeReservacionesPage);

    }

    private void changePanel(java.awt.event.ActionEvent evt) {
        if (evt.getActionCommand().equals(menuReservasBtn.getActionCommand())) {
            content.setSelectedIndex(0);
        } else if (evt.getActionCommand().equals(menuReservarBtn.getActionCommand())) {
            content.setSelectedIndex(1);
        } else {
            content.setSelectedIndex(2);
        }
        toggleMenu();
    }

    private void toggleMenu() {
        Kensoft animate = new Kensoft();
        if (menu.getLocation().x == 0) {
            animate.jPanelXLeft(0, -180, 1, 1, menu);
        } else {
            animate.jPanelXRight(-180, 0, 1, 1, menu);
        }
    }

    private void loadPerfil() {
        documentoText.setText(clienteLogged.getDocumento());
        nombreText.setText(clienteLogged.getNombre());
        emailText.setText(clienteLogged.getEmail());
        passText.setText(clienteLogged.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JPanel();
        logoImg = new javax.swing.JLabel();
        menuButton = new javax.swing.JLabel();
        loggedUserNameLabel = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        menuReservasBtn = new javax.swing.JButton();
        menuReservarBtn = new javax.swing.JButton();
        menuPerfilBtn = new javax.swing.JButton();
        content = new javax.swing.JTabbedPane();
        mainPanel = new javax.swing.JPanel();
        mainReservacionesPagPanel = new javax.swing.JPanel();
        reservacionesPrevBtn = new javax.swing.JButton();
        reservacionesPagLabel = new javax.swing.JLabel();
        reservacionesNextBtn = new javax.swing.JButton();
        mainReservacionesPanel = new javax.swing.JPanel();
        mainBackground = new javax.swing.JLabel();
        reservasPanel = new javax.swing.JPanel();
        perfilPanel = new javax.swing.JPanel();
        perfilFormPanel = new javax.swing.JPanel();
        documentoLabel = new javax.swing.JLabel();
        documentoText = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        passText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        editButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toolbar.setBackground(new java.awt.Color(0, 0, 0));
        toolbar.setMaximumSize(new java.awt.Dimension(910, 80));
        toolbar.setMinimumSize(new java.awt.Dimension(910, 80));

        logoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logonombre.png"))); // NOI18N

        menuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_menu.png"))); // NOI18N
        menuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuButtonMouseClicked(evt);
            }
        });

        loggedUserNameLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        loggedUserNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        loggedUserNameLabel.setText("Bienvenid@");

        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_logout.png"))); // NOI18N
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout toolbarLayout = new javax.swing.GroupLayout(toolbar);
        toolbar.setLayout(toolbarLayout);
        toolbarLayout.setHorizontalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(menuButton)
                .addGap(18, 18, 18)
                .addComponent(loggedUserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(logoImg)
                .addGap(16, 16, 16)
                .addComponent(logoutBtn)
                .addGap(16, 16, 16))
        );
        toolbarLayout.setVerticalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(logoImg))
            .addGroup(toolbarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loggedUserNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addGap(18, 18, 18))
        );

        getContentPane().add(toolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        menu.setBackground(new java.awt.Color(0, 0, 0, 220));
        menu.setMaximumSize(new java.awt.Dimension(180, 720));
        menu.setMinimumSize(new java.awt.Dimension(180, 720));
        menu.setPreferredSize(new java.awt.Dimension(180, 720));

        menuReservasBtn.setBackground(new java.awt.Color(51, 51, 51));
        menuReservasBtn.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        menuReservasBtn.setForeground(new java.awt.Color(255, 255, 255));
        menuReservasBtn.setText("Mis Reservas");
        menuReservasBtn.setBorderPainted(false);
        menuReservasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuReservasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReservasBtnActionPerformed(evt);
            }
        });

        menuReservarBtn.setBackground(new java.awt.Color(51, 51, 51));
        menuReservarBtn.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        menuReservarBtn.setForeground(new java.awt.Color(255, 255, 255));
        menuReservarBtn.setText("Reservar");
        menuReservarBtn.setBorderPainted(false);
        menuReservarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuReservarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReservarBtnActionPerformed(evt);
            }
        });

        menuPerfilBtn.setBackground(new java.awt.Color(51, 51, 51));
        menuPerfilBtn.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        menuPerfilBtn.setForeground(new java.awt.Color(255, 255, 255));
        menuPerfilBtn.setText("Perfil");
        menuPerfilBtn.setBorderPainted(false);
        menuPerfilBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuPerfilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPerfilBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuReservasBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(menuReservarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuPerfilBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(menuReservasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuReservarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPerfilBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(433, Short.MAX_VALUE))
        );

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, 180, 720));

        content.setEnabled(false);
        content.setMaximumSize(new java.awt.Dimension(900, 680));
        content.setMinimumSize(new java.awt.Dimension(900, 680));
        content.setPreferredSize(new java.awt.Dimension(900, 680));

        mainPanel.setMaximumSize(new java.awt.Dimension(1080, 645));
        mainPanel.setMinimumSize(new java.awt.Dimension(1080, 645));
        mainPanel.setPreferredSize(new java.awt.Dimension(1080, 645));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainReservacionesPagPanel.setLayout(new java.awt.GridLayout(1, 3));

        reservacionesPrevBtn.setText("<");
        reservacionesPrevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservacionesPrevBtnActionPerformed(evt);
            }
        });
        mainReservacionesPagPanel.add(reservacionesPrevBtn);

        reservacionesPagLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservacionesPagLabel.setText("Página (1/1)");
        mainReservacionesPagPanel.add(reservacionesPagLabel);

        reservacionesNextBtn.setText(">");
        mainReservacionesPagPanel.add(reservacionesNextBtn);

        mainPanel.add(mainReservacionesPagPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 590, 648, 30));

        mainReservacionesPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainReservacionesPanel.setLayout(new java.awt.GridLayout(5, 1));
        mainPanel.add(mainReservacionesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 64, 648, 516));

        mainBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicio.jpg"))); // NOI18N
        mainPanel.add(mainBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, -1, -1));

        content.addTab("tab1", mainPanel);

        reservasPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        content.addTab("tab2", reservasPanel);

        perfilFormPanel.setLayout(new java.awt.GridLayout(10, 1));

        documentoLabel.setText("Documento");
        perfilFormPanel.add(documentoLabel);

        documentoText.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        documentoText.setEnabled(false);
        perfilFormPanel.add(documentoText);

        nombreLabel.setText("Nombre");
        perfilFormPanel.add(nombreLabel);

        nombreText.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nombreText.setEnabled(false);
        perfilFormPanel.add(nombreText);

        emailLabel.setText("Email");
        perfilFormPanel.add(emailLabel);

        emailText.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        emailText.setEnabled(false);
        perfilFormPanel.add(emailText);

        passLabel.setText("Contraseña");
        perfilFormPanel.add(passLabel);

        passText.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        passText.setEnabled(false);
        perfilFormPanel.add(passText);
        perfilFormPanel.add(jSeparator1);

        editButton.setText("Editar");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        perfilFormPanel.add(editButton);

        javax.swing.GroupLayout perfilPanelLayout = new javax.swing.GroupLayout(perfilPanel);
        perfilPanel.setLayout(perfilPanelLayout);
        perfilPanelLayout.setHorizontalGroup(
            perfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perfilPanelLayout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(perfilFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        perfilPanelLayout.setVerticalGroup(
            perfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perfilPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(perfilFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        content.addTab("tab3", perfilPanel);

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1080, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuButtonMouseClicked
        toggleMenu();
    }//GEN-LAST:event_menuButtonMouseClicked

    private void reservacionesPrevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservacionesPrevBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservacionesPrevBtnActionPerformed

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        int result = JOptionPane.showConfirmDialog(this,
                "¿Está seguro que desea cerrar la sesión?",
                "Cerrar sesión",
                JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.YES_OPTION) {
            InicialUI inicialUI = new InicialUI();
            inicialUI.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void menuReservasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReservasBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuReservasBtnActionPerformed

    private void menuReservarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReservarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuReservarBtnActionPerformed

    private void menuPerfilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPerfilBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPerfilBtnActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        if (editButton.getText().equals("Editar")) {
            nombreText.setEnabled(true);
            passText.setEnabled(true);
            editButton.setText("Guardar");
        } else {

            if (!nombreText.getText().isEmpty() && !passText.getText().isEmpty()) {

                int index = -1;
                for (int i = 0; i < Main.clientes().size(); i++) {
                    Cliente cliente = Main.clientes().get(i);
                    if (cliente.getDocumento().equals(clienteLogged.getDocumento())) {
                        index = i;
                    }
                }
                
                clienteLogged.setNombre(nombreText.getText());
                clienteLogged.setPassword(passText.getText());
                Main.hotel.getClientes().actualizar(index, clienteLogged);

                nombreText.setEnabled(false);
                passText.setEnabled(false);
                editButton.setText("Edit");
            } else {
                JOptionPane.showMessageDialog(this, "Debe llenar todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void cargarReservaciones() {
        contentHabitaciones.cargarHabitaciones();
        mainReservacionesPanel.removeAll();
        mainReservacionesPanel.revalidate();
        mainReservacionesPanel.repaint();
        List<Reservacion> filtrados;
        if (this.clienteLogged.getReservas().size() <= MAX_PER_PAGE) {
            filtrados = this.clienteLogged.getReservas();
        } else {
            int inicio = reservacionespaginaActual * MAX_PER_PAGE;
            int fin = inicio + MAX_PER_PAGE;
            if (fin > this.clienteLogged.getReservas().size()) {
                fin = this.clienteLogged.getReservas().size();
            }
            filtrados = this.clienteLogged.getReservas().subList(inicio, fin);
        }
        for (Reservacion reservacion : filtrados) {
            mainReservacionesPanel.add(buildReservacionCard(reservacion));
        }
        int paginaActual = reservacionespaginaActual + 1;
        reservacionesPagLabel.setText("Página (" + paginaActual + "/" + reservacionesPaginasTotales + ")");
    }

    private javax.swing.JPanel buildReservacionCard(Reservacion reservacion) {
        Habitacion habitacion = reservacion.getHabitacion();
        javax.swing.JPanel reservacionCard = new javax.swing.JPanel();
        javax.swing.JLabel habitacionLabel = new javax.swing.JLabel();
        javax.swing.JLabel habitacionValue = new javax.swing.JLabel();
        javax.swing.JLabel precioNocheLabel = new javax.swing.JLabel();
        javax.swing.JLabel precioNocheValue = new javax.swing.JLabel();
        javax.swing.JLabel fechasLabel = new javax.swing.JLabel();
        javax.swing.JLabel fechasValue = new javax.swing.JLabel();
        javax.swing.JLabel estadoLabel = new javax.swing.JLabel();
        javax.swing.JLabel estadoValue = new javax.swing.JLabel();
        javax.swing.JLabel totalLabel = new javax.swing.JLabel();
        javax.swing.JLabel totalValue = new javax.swing.JLabel();

        reservacionCard.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        reservacionCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        habitacionLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        habitacionLabel.setText("Habitacion:");
        reservacionCard.add(habitacionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        habitacionValue.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        habitacionValue.setText("" + habitacion.getNumero() + " (" + habitacion.getTipo().name() + ")");
        reservacionCard.add(habitacionValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        precioNocheLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        precioNocheLabel.setText("Precio por noche:");
        reservacionCard.add(precioNocheLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        precioNocheValue.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        precioNocheValue.setText("$ " + habitacion.getPrecioPorNoche());
        reservacionCard.add(precioNocheValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        fechasLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        fechasLabel.setText("Fechas:");
        reservacionCard.add(fechasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        fechasValue.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        String inicio = df.format(reservacion.getFechaInicio());
        String fin = df.format(reservacion.getFechaFin());
        fechasValue.setText(inicio + " - " + fin + " (" + reservacion.getDias() + " noches)");
        reservacionCard.add(fechasValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        estadoLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        estadoLabel.setText("Estado de la reserva:");
        reservacionCard.add(estadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        estadoValue.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        estadoValue.setText(reservacion.getEstado().name());
        reservacionCard.add(estadoValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        totalLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        totalLabel.setText("Total pagado:");
        reservacionCard.add(totalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        totalValue.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        totalValue.setText("$ " + reservacion.getPago().getMonto() + " (" + reservacion.getPago().getTipo().name() + ")");
        reservacionCard.add(totalValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        return reservacionCard;
    }

    private void changeReservacionesPage(java.awt.event.ActionEvent evt) {
        if (evt.getActionCommand().equals(reservacionesNextBtn.getActionCommand())) {
            if (reservacionespaginaActual < reservacionesPaginasTotales - 1) {
                reservacionespaginaActual++;
                cargarReservaciones();
            }
        } else {
            if (reservacionespaginaActual > 0) {
                reservacionespaginaActual--;
                cargarReservaciones();
            }
        }

    }

    private HabitacionesPanel contentHabitaciones;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane content;
    private javax.swing.JLabel documentoLabel;
    private javax.swing.JTextField documentoText;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel loggedUserNameLabel;
    private javax.swing.JLabel logoImg;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JLabel mainBackground;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainReservacionesPagPanel;
    private javax.swing.JPanel mainReservacionesPanel;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel menuButton;
    private javax.swing.JButton menuPerfilBtn;
    private javax.swing.JButton menuReservarBtn;
    private javax.swing.JButton menuReservasBtn;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreText;
    private javax.swing.JLabel passLabel;
    private javax.swing.JTextField passText;
    private javax.swing.JPanel perfilFormPanel;
    private javax.swing.JPanel perfilPanel;
    private javax.swing.JButton reservacionesNextBtn;
    private javax.swing.JLabel reservacionesPagLabel;
    private javax.swing.JButton reservacionesPrevBtn;
    private javax.swing.JPanel reservasPanel;
    private javax.swing.JPanel toolbar;
    // End of variables declaration//GEN-END:variables
}
