package GUI;

import GUI.panel.HabitacionesPanel;
import KentHipos.Kensoft;
import static javax.swing.SwingConstants.CENTER;
import modelo.Cliente;
import modelo.Empleado;
import sistemareserva.Main;

/**
 *
 * @author Usuario
 */
public class InicialUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public InicialUI() {
        initComponents();
        
        contentHabitaciones = new HabitacionesPanel(this);
        contentHabitaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        body3home.add(contentHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 640));

        menuHomeBtn.addActionListener(this::changePanel);
        menuLoginBtn.addActionListener(this::changePanel);
        menuAboutBtn.addActionListener(this::changePanel);

        loginActionBtn.addActionListener(this::loginAction);
        
        homecreation();
        Aboutuscreation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        toolbar = new javax.swing.JPanel();
        logoImg = new javax.swing.JLabel();
        menuButton = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        menuHomeBtn = new javax.swing.JButton();
        menuLoginBtn = new javax.swing.JButton();
        menuAboutBtn = new javax.swing.JButton();
        content = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        borderhedadhome = new javax.swing.JPanel();
        scrollHomepage = new javax.swing.JScrollPane();
        ContentHomeScroll = new javax.swing.JPanel();
        body1home = new javax.swing.JPanel();
        fraseHome = new javax.swing.JLabel();
        backgroundhome = new javax.swing.JLabel();
        body2home = new javax.swing.JPanel();
        foto2bodyhome = new javax.swing.JLabel();
        fot2bodyhome2 = new javax.swing.JLabel();
        titulo2bodyhome = new javax.swing.JLabel();
        descripcionHotelhome2body = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        body3home = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        loginFormPanel = new javax.swing.JPanel();
        loginEmailLabel = new javax.swing.JLabel();
        loginEmailText = new javax.swing.JTextField();
        loginPasswordLabel = new javax.swing.JLabel();
        loginPasswordText = new javax.swing.JPasswordField();
        loginActionBtn = new javax.swing.JButton();
        loginErrorMessage = new javax.swing.JLabel();
        loginBackground = new javax.swing.JLabel();
        aboutPanel = new javax.swing.JPanel();
        scrollAboutpage1 = new javax.swing.JScrollPane();
        ContentAboutScroll1 = new javax.swing.JPanel();
        body1About1 = new javax.swing.JPanel();
        AboutusText = new javax.swing.JLabel();
        titleSobrenosotrosAbout = new javax.swing.JLabel();
        backgroundAbout = new javax.swing.JLabel();
        body2About1 = new javax.swing.JPanel();
        backbody2about = new javax.swing.JLabel();
        Nuestrahistoriatext = new javax.swing.JLabel();
        Nuestramisiontext = new javax.swing.JLabel();
        nuestrahistoria = new javax.swing.JLabel();
        nuestramision = new javax.swing.JLabel();
        body3About1 = new javax.swing.JPanel();
        aboutfoto2 = new javax.swing.JLabel();
        aboutfoto1 = new javax.swing.JLabel();
        Nuestrahistoriatext1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        dirreccion = new javax.swing.JLabel();
        telefonomovil = new javax.swing.JLabel();
        fax = new javax.swing.JLabel();
        nit = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        uperinformationboarder = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toolbar.setBackground(new java.awt.Color(0, 0, 0));
        toolbar.setMaximumSize(new java.awt.Dimension(910, 80));
        toolbar.setMinimumSize(new java.awt.Dimension(910, 80));

        logoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logonombre.png"))); // NOI18N

        menuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_menu.png"))); // NOI18N
        menuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout toolbarLayout = new javax.swing.GroupLayout(toolbar);
        toolbar.setLayout(toolbarLayout);
        toolbarLayout.setHorizontalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(menuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 734, Short.MAX_VALUE)
                .addComponent(logoImg)
                .addGap(56, 56, 56))
        );
        toolbarLayout.setVerticalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarLayout.createSequentialGroup()
                .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoImg, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(toolbarLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(menuButton)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(toolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        menu.setBackground(new java.awt.Color(0, 0, 0, 190));
        menu.setMaximumSize(new java.awt.Dimension(180, 720));
        menu.setMinimumSize(new java.awt.Dimension(180, 720));
        menu.setPreferredSize(new java.awt.Dimension(180, 720));

        menuHomeBtn.setBackground(new java.awt.Color(51, 51, 51));
        menuHomeBtn.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        menuHomeBtn.setForeground(new java.awt.Color(255, 255, 255));
        menuHomeBtn.setText("Home");
        menuHomeBtn.setBorderPainted(false);
        menuHomeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHomeBtnActionPerformed(evt);
            }
        });

        menuLoginBtn.setBackground(new java.awt.Color(51, 51, 51));
        menuLoginBtn.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        menuLoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        menuLoginBtn.setText("Iniciar Sesión");
        menuLoginBtn.setBorderPainted(false);
        menuLoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuAboutBtn.setBackground(new java.awt.Color(51, 51, 51));
        menuAboutBtn.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        menuAboutBtn.setForeground(new java.awt.Color(255, 255, 255));
        menuAboutBtn.setText("Acerca de");
        menuAboutBtn.setBorderPainted(false);
        menuAboutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuHomeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuLoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(menuAboutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(menuHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuAboutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(433, Short.MAX_VALUE))
        );

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, 180, 720));

        content.setEnabled(false);
        content.setMaximumSize(new java.awt.Dimension(900, 680));
        content.setMinimumSize(new java.awt.Dimension(900, 680));
        content.setPreferredSize(new java.awt.Dimension(900, 680));

        homePanel.setMaximumSize(new java.awt.Dimension(1080, 645));
        homePanel.setMinimumSize(new java.awt.Dimension(1080, 645));
        homePanel.setPreferredSize(new java.awt.Dimension(1080, 645));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        borderhedadhome.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout borderhedadhomeLayout = new javax.swing.GroupLayout(borderhedadhome);
        borderhedadhome.setLayout(borderhedadhomeLayout);
        borderhedadhomeLayout.setHorizontalGroup(
            borderhedadhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        borderhedadhomeLayout.setVerticalGroup(
            borderhedadhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        homePanel.add(borderhedadhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1070, 20));

        scrollHomepage.setBorder(null);
        scrollHomepage.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollHomepage.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollHomepage.setHorizontalScrollBar(null);
        scrollHomepage.setPreferredSize(new java.awt.Dimension(1080, 1890));

        ContentHomeScroll.setBackground(new java.awt.Color(0, 0, 0));
        ContentHomeScroll.setPreferredSize(new java.awt.Dimension(1070, 1930));
        ContentHomeScroll.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body1home.setBackground(new java.awt.Color(0, 0, 0));
        body1home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fraseHome.setFont(new java.awt.Font("Constantia", 1, 48)); // NOI18N
        fraseHome.setForeground(new java.awt.Color(255, 255, 255));
        fraseHome.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        body1home.add(fraseHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 400, 180));

        backgroundhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/homebackground.jpg"))); // NOI18N
        body1home.add(backgroundhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 630));

        ContentHomeScroll.add(body1home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 630));

        body2home.setBackground(new java.awt.Color(0, 0, 0));
        body2home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foto2bodyhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/homepage2body2.jpg"))); // NOI18N
        body2home.add(foto2bodyhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 300, 440));

        fot2bodyhome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/homepage2body.jpg"))); // NOI18N
        fot2bodyhome2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        fot2bodyhome2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        body2home.add(fot2bodyhome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 430, 660));

        titulo2bodyhome.setFont(new java.awt.Font("Constantia", 3, 24)); // NOI18N
        titulo2bodyhome.setForeground(new java.awt.Color(255, 255, 255));
        body2home.add(titulo2bodyhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 290, 90));

        descripcionHotelhome2body.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        descripcionHotelhome2body.setForeground(new java.awt.Color(255, 255, 255,180));
        body2home.add(descripcionHotelhome2body, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 330, 360));

        jButton1.setBackground(new java.awt.Color(231, 231, 231));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Leer Mas ");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        body2home.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, 90, 40));

        ContentHomeScroll.add(body2home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1070, 660));

        body3home.setBackground(new java.awt.Color(0, 0, 0,160));
        body3home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ContentHomeScroll.add(body3home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1290, 1070, 640));

        scrollHomepage.setViewportView(ContentHomeScroll);

        homePanel.add(scrollHomepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1080, 630));

        content.addTab("tab1", homePanel);

        loginPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginFormPanel.setBackground(new java.awt.Color(0, 0, 0, 210));
        loginFormPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inicio de Sesión", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        loginEmailLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        loginEmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginEmailLabel.setText("Email");

        loginEmailText.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        loginEmailText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        loginEmailText.setBorder(null);

        loginPasswordLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        loginPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginPasswordLabel.setText("Contraseña");

        loginPasswordText.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        loginPasswordText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        loginPasswordText.setBorder(null);

        loginActionBtn.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        loginActionBtn.setText("Iniciar Sesión");
        loginActionBtn.setBorder(null);
        loginActionBtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        loginErrorMessage.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        loginErrorMessage.setForeground(new java.awt.Color(204, 51, 0));
        loginErrorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout loginFormPanelLayout = new javax.swing.GroupLayout(loginFormPanel);
        loginFormPanel.setLayout(loginFormPanelLayout);
        loginFormPanelLayout.setHorizontalGroup(
            loginFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFormPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(loginFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginEmailLabel)
                    .addComponent(loginEmailText)
                    .addComponent(loginPasswordLabel)
                    .addComponent(loginActionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(loginPasswordText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginFormPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loginErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        loginFormPanelLayout.setVerticalGroup(
            loginFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFormPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(loginEmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(loginActionBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(loginErrorMessage)
                .addContainerGap())
        );

        loginPanel.add(loginFormPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 129, 648, 387));

        loginBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicio.jpg"))); // NOI18N
        loginPanel.add(loginBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, -1, 710));

        content.addTab("tab2", loginPanel);

        aboutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollAboutpage1.setBorder(null);
        scrollAboutpage1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollAboutpage1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollAboutpage1.setHorizontalScrollBar(null);
        scrollAboutpage1.setPreferredSize(new java.awt.Dimension(1080, 1890));

        ContentAboutScroll1.setBackground(new java.awt.Color(0, 0, 0));
        ContentAboutScroll1.setPreferredSize(new java.awt.Dimension(1080, 1930));
        ContentAboutScroll1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body1About1.setBackground(new java.awt.Color(0, 0, 0));
        body1About1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AboutusText.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        AboutusText.setForeground(new java.awt.Color(255, 255, 255));
        AboutusText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AboutusText.setToolTipText("");
        AboutusText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        body1About1.add(AboutusText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 920, 250));

        titleSobrenosotrosAbout.setBackground(new java.awt.Color(0, 0, 0));
        titleSobrenosotrosAbout.setFont(new java.awt.Font("Constantia", 3, 48)); // NOI18N
        titleSobrenosotrosAbout.setForeground(new java.awt.Color(255, 255, 255));
        titleSobrenosotrosAbout.setText("Sobre Nosostros");
        body1About1.add(titleSobrenosotrosAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 380, 80));

        backgroundAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Aboutus.jpg"))); // NOI18N
        backgroundAbout.setText("jLabel1");
        body1About1.add(backgroundAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 315));

        ContentAboutScroll1.add(body1About1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 630));

        body2About1.setBackground(new java.awt.Color(0, 0, 0));
        body2About1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backbody2about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Nuestrahistoria.jpg"))); // NOI18N
        body2About1.add(backbody2about, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 0, 410, 660));

        Nuestrahistoriatext.setBackground(new java.awt.Color(0, 0, 0));
        Nuestrahistoriatext.setFont(new java.awt.Font("SansSerif", 2, 24)); // NOI18N
        Nuestrahistoriatext.setForeground(new java.awt.Color(255, 255, 255));
        Nuestrahistoriatext.setText("Nuestra Historia ");
        body2About1.add(Nuestrahistoriatext, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 190, 50));

        Nuestramisiontext.setBackground(new java.awt.Color(0, 0, 0));
        Nuestramisiontext.setFont(new java.awt.Font("SansSerif", 2, 24)); // NOI18N
        Nuestramisiontext.setForeground(new java.awt.Color(255, 255, 255));
        Nuestramisiontext.setText("Nuestra Misión");
        body2About1.add(Nuestramisiontext, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 160, 50));

        nuestrahistoria.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        nuestrahistoria.setForeground(new java.awt.Color(255, 255, 255));
        body2About1.add(nuestrahistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 500, 230));

        nuestramision.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        nuestramision.setForeground(new java.awt.Color(255, 255, 255));
        body2About1.add(nuestramision, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 500, 230));

        ContentAboutScroll1.add(body2About1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1070, 660));

        body3About1.setBackground(new java.awt.Color(0, 0, 0));
        body3About1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aboutfoto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutfoto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aboutus4.jpg"))); // NOI18N
        body3About1.add(aboutfoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 310, 330));

        aboutfoto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutfoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aboutus3.jpg"))); // NOI18N
        aboutfoto1.setToolTipText("");
        aboutfoto1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        body3About1.add(aboutfoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 300, 360));

        Nuestrahistoriatext1.setBackground(new java.awt.Color(0, 0, 0));
        Nuestrahistoriatext1.setFont(new java.awt.Font("SansSerif", 2, 24)); // NOI18N
        Nuestrahistoriatext1.setForeground(new java.awt.Color(255, 255, 255));
        Nuestrahistoriatext1.setText("Nuestros Servicios ");
        body3About1.add(Nuestrahistoriatext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 210, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/servicios.jpg"))); // NOI18N
        body3About1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 240, 410));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(nombre);

        dirreccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(dirreccion);

        telefonomovil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(telefonomovil);

        fax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(fax);

        nit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(nit);

        email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(email);

        body3About1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 1070, 90));

        uperinformationboarder.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout uperinformationboarderLayout = new javax.swing.GroupLayout(uperinformationboarder);
        uperinformationboarder.setLayout(uperinformationboarderLayout);
        uperinformationboarderLayout.setHorizontalGroup(
            uperinformationboarderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        uperinformationboarderLayout.setVerticalGroup(
            uperinformationboarderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        body3About1.add(uperinformationboarder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 1070, 10));

        ContentAboutScroll1.add(body3About1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1290, 1070, 640));

        scrollAboutpage1.setViewportView(ContentAboutScroll1);

        aboutPanel.add(scrollAboutpage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1080, 630));

        content.addTab("tab3", aboutPanel);

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1080, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toggleMenu() {
        Kensoft animate = new Kensoft();
        if (menu.getLocation().x == 0) {
            animate.jPanelXLeft(0, -180, 1, 1, menu);
        } else {
            animate.jPanelXRight(-180, 0, 1, 1, menu);
        }
    }

    private void menuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuButtonMouseClicked
        toggleMenu();
    }//GEN-LAST:event_menuButtonMouseClicked

    private void menuHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHomeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHomeBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        content.setSelectedIndex(2);
    }//GEN-LAST:event_jButton1MouseClicked

    private void changePanel(java.awt.event.ActionEvent evt) {
        if (evt.getActionCommand().equals(menuHomeBtn.getActionCommand())) {
            content.setSelectedIndex(0);
        } else if (evt.getActionCommand().equals(menuLoginBtn.getActionCommand())) {
            content.setSelectedIndex(1);
        } else {
            content.setSelectedIndex(2);
        }
        toggleMenu();
    }

    private void loginAction(java.awt.event.ActionEvent evt) {
        loginErrorMessage.setText("");
        String email = loginEmailText.getText();
        String pass = new String(loginPasswordText.getPassword());

        Empleado empleadoLogged = null;
        Cliente clienteLogged = null;

        for (Empleado empleado : Main.empleados()) {
            if (empleado.getEmail().equals(email)) {
                if (empleado.getPassword().equals(pass)) {
                    empleadoLogged = empleado;
                }
            }
        }

        for (Cliente cliente : Main.clientes()) {
            if (cliente.getEmail().equals(email)) {
                if (cliente.getPassword().equals(pass)) {
                    clienteLogged = cliente;
                }
            }
        }
        
        if(empleadoLogged != null) {
            EmpleadoUI empleadoUI = new EmpleadoUI(empleadoLogged);
            empleadoUI.setVisible(true);
            dispose();
        } else if (clienteLogged != null) {
            ClienteUI cliente = new ClienteUI(clienteLogged);
            cliente.setVisible(true);
            dispose();
        } else {
            loginErrorMessage.setText("usuario o contraseña incorrectos");
        }
    }
    
    private void homecreation() {

        fraseHome.setText("<html><p>Vive la Experiencia,<br>" + Main.hotel.getNombre() + "</p></html>");
        titulo2bodyhome.setText("<html><p>Bienvenido a " + Main.hotel.getNombre() + "</p></html>");
        descripcionHotelhome2body.setText("<html>" + Main.hotel.getDescripcion());
        
        contentHabitaciones.cargarHabitaciones();
        //cargarHabitaciones();

    }
    
    private void Aboutuscreation(){
    AboutusText.setText("<html><p style='text-align: center;'>Ubicado en el corazón de un paraíso exótico,<br> Paradise Hotel ofrece una experiencia inigualable de lujo, confort y serenidad.<br>"
            + "Nuestro hotel es un refugio para viajeros que buscan una estadía inolvidable,<br> ya sea por placer, negocios o una ocasión especial.<br>"
            + "En Paradise Hotel,nos enorgullece ofrecer un servicio excepcional,<br>alojamientos elegantes y comodidades de clase mundial.</html>");
  
    
    nuestramision.setText("<html><p style='text-align: center;'>Nuestra misión en Paradise Hotel es ofrecer una experiencia de huésped excepcional que supere las expectativas.<br>"
            + "Queremos crear recuerdos duraderos proporcionando un servicio sobresaliente,<br>"
            + "alojamientos lujosos y una variedad de comodidades adaptadas para satisfacer las diversas necesidades de nuestros huéspedes.<br>"
            + "Estamos dedicados a hacer que su estadía con nosotros sea una experiencia verdaderamente inolvidable.</html>");
    
    nuestrahistoria.setText("<html><p style='text-align: center;'>Paradise Hotel fue fundado con la visión de crear un santuario donde los huéspedes puedan escapar del ajetreo y el bullicio de la vida cotidiana.<br>"
            + "Desde nuestro inicio, hemos estado comprometidos con ofrecer una combinación única de hospitalidad tradicional y confort moderno.<br>"
            + " Nuestra pasión por la excelencia se refleja en cada detalle,<br>"
            + "desde nuestros interiores meticulosamente diseñados hasta nuestros servicios personalizados para los huéspedes.");
    nombre.setText( Main.hotel.getNombre() );
    dirreccion.setText(Main.hotel.getDireccion());
    telefonomovil.setText("Telefono: " + Main.hotel.getTelefono() + "  Movil: " + Main.hotel.getMovil());
    fax.setText(Main.hotel.getFax());
    nit.setText(Main.hotel.getNit());
    email.setText(Main.hotel.getEmail());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicialUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicialUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicialUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicialUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InicialUI().setVisible(true);
        });
    }

    private HabitacionesPanel contentHabitaciones;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutusText;
    private javax.swing.JPanel ContentAboutScroll1;
    private javax.swing.JPanel ContentHomeScroll;
    private javax.swing.JLabel Nuestrahistoriatext;
    private javax.swing.JLabel Nuestrahistoriatext1;
    private javax.swing.JLabel Nuestramisiontext;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JLabel aboutfoto1;
    private javax.swing.JLabel aboutfoto2;
    private javax.swing.JLabel backbody2about;
    private javax.swing.JLabel backgroundAbout;
    private javax.swing.JLabel backgroundhome;
    private javax.swing.JPanel body1About1;
    private javax.swing.JPanel body1home;
    private javax.swing.JPanel body2About1;
    private javax.swing.JPanel body2home;
    private javax.swing.JPanel body3About1;
    private javax.swing.JPanel body3home;
    private javax.swing.JPanel borderhedadhome;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTabbedPane content;
    private javax.swing.JLabel descripcionHotelhome2body;
    private javax.swing.JLabel dirreccion;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fax;
    private javax.swing.JLabel fot2bodyhome2;
    private javax.swing.JLabel foto2bodyhome;
    private javax.swing.JLabel fraseHome;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginActionBtn;
    private javax.swing.JLabel loginBackground;
    private javax.swing.JLabel loginEmailLabel;
    private javax.swing.JTextField loginEmailText;
    private javax.swing.JLabel loginErrorMessage;
    private javax.swing.JPanel loginFormPanel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel loginPasswordLabel;
    private javax.swing.JPasswordField loginPasswordText;
    private javax.swing.JLabel logoImg;
    private javax.swing.JPanel menu;
    private javax.swing.JButton menuAboutBtn;
    private javax.swing.JLabel menuButton;
    private javax.swing.JButton menuHomeBtn;
    private javax.swing.JButton menuLoginBtn;
    private javax.swing.JLabel nit;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nuestrahistoria;
    private javax.swing.JLabel nuestramision;
    private javax.swing.JScrollPane scrollAboutpage1;
    private javax.swing.JScrollPane scrollHomepage;
    private javax.swing.JLabel telefonomovil;
    private javax.swing.JLabel titleSobrenosotrosAbout;
    private javax.swing.JLabel titulo2bodyhome;
    private javax.swing.JPanel toolbar;
    private javax.swing.JPanel uperinformationboarder;
    // End of variables declaration//GEN-END:variables
}