/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import enums.TipoPago;
import java.util.Date;
import modelo.Cliente;
import modelo.Habitacion;

/**
 *
 * @author Usuario
 */
import modelo.Reservacion;
import sistemareserva.Main;

public class Reserva extends javax.swing.JFrame {

    TipoPago selectedTipopago;

    /**
     * Creates new form Reserva
     */
    public Reserva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        contentReserva = new javax.swing.JPanel();
        visualHabitacionReservar = new javax.swing.JPanel();
        datosClientereservacontent = new javax.swing.JPanel();
        labelDatosPersonales = new javax.swing.JLabel();
        NombreDatosPersonales = new javax.swing.JTextField();
        DocumentoDatosPersonales = new javax.swing.JTextField();
        EmailDatosPersonales = new javax.swing.JTextField();
        Nombrelabel = new javax.swing.JLabel();
        Documentolabel = new javax.swing.JLabel();
        Emaillabel = new javax.swing.JLabel();
        reservacontent = new javax.swing.JPanel();
        DatosReservacontent = new javax.swing.JPanel();
        labelDatosReserva = new javax.swing.JLabel();
        Dateinicio = new com.toedter.calendar.JDateChooser();
        Datefin = new com.toedter.calendar.JDateChooser();
        findelareservalabel = new javax.swing.JLabel();
        iniciodelareservalabel = new javax.swing.JLabel();
        datosPagoreservacontent = new javax.swing.JPanel();
        labelDatosReserva1 = new javax.swing.JLabel();
        Totallabel = new javax.swing.JLabel();
        tipoPagolabel = new javax.swing.JLabel();
        ComboboxTipopago = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        realizarReservacion = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentReserva.setBackground(new java.awt.Color(255, 255, 255));
        contentReserva.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout visualHabitacionReservarLayout = new javax.swing.GroupLayout(visualHabitacionReservar);
        visualHabitacionReservar.setLayout(visualHabitacionReservarLayout);
        visualHabitacionReservarLayout.setHorizontalGroup(
            visualHabitacionReservarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        visualHabitacionReservarLayout.setVerticalGroup(
            visualHabitacionReservarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        contentReserva.add(visualHabitacionReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 91, -1, -1));

        labelDatosPersonales.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDatosPersonales.setText("Datos Personales:");

        NombreDatosPersonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreDatosPersonalesActionPerformed(evt);
            }
        });

        Nombrelabel.setText("Nombre :");

        Documentolabel.setText("Documento:");

        Emaillabel.setText("Email:");

        javax.swing.GroupLayout datosClientereservacontentLayout = new javax.swing.GroupLayout(datosClientereservacontent);
        datosClientereservacontent.setLayout(datosClientereservacontentLayout);
        datosClientereservacontentLayout.setHorizontalGroup(
            datosClientereservacontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosClientereservacontentLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(datosClientereservacontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosClientereservacontentLayout.createSequentialGroup()
                        .addComponent(labelDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosClientereservacontentLayout.createSequentialGroup()
                        .addGroup(datosClientereservacontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NombreDatosPersonales, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(datosClientereservacontentLayout.createSequentialGroup()
                                .addGroup(datosClientereservacontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DocumentoDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Documentolabel)
                                    .addComponent(Nombrelabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(datosClientereservacontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Emaillabel)
                                    .addComponent(EmailDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27))))
        );
        datosClientereservacontentLayout.setVerticalGroup(
            datosClientereservacontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosClientereservacontentLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nombrelabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(datosClientereservacontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Documentolabel)
                    .addComponent(Emaillabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosClientereservacontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DocumentoDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        contentReserva.add(datosClientereservacontent, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 70, -1, 210));

        reservacontent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DatosReservacontent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDatosReserva.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDatosReserva.setText("Detalles De La Reserva :");
        DatosReservacontent.add(labelDatosReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        DatosReservacontent.add(Dateinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 270, 40));
        DatosReservacontent.add(Datefin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 280, 40));

        findelareservalabel.setText("Fin de la reservacion:");
        DatosReservacontent.add(findelareservalabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        iniciodelareservalabel.setText("Inicio de la reservacion:");
        DatosReservacontent.add(iniciodelareservalabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 130, 20));

        reservacontent.add(DatosReservacontent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 140));

        datosPagoreservacontent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDatosReserva1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDatosReserva1.setText("Detalles Del Pago :");
        datosPagoreservacontent.add(labelDatosReserva1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        Totallabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Totallabel.setToolTipText("");
        datosPagoreservacontent.add(Totallabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 160, 20));

        tipoPagolabel.setText("Tipo pago :");
        datosPagoreservacontent.add(tipoPagolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        datosPagoreservacontent.add(ComboboxTipopago, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 190, -1));
        datosPagoreservacontent.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 100, 20));

        reservacontent.add(datosPagoreservacontent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 650, 130));

        contentReserva.add(reservacontent, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 320, 652, -1));

        realizarReservacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        realizarReservacion.setText("Reservar");
        realizarReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarReservacionActionPerformed(evt);
            }
        });
        contentReserva.add(realizarReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 509, 246, 47));

        getContentPane().add(contentReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreDatosPersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreDatosPersonalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreDatosPersonalesActionPerformed

    private void realizarReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarReservacionActionPerformed


    }//GEN-LAST:event_realizarReservacionActionPerformed

    private void ReservaMotion (){
        
    }
    private void reservaAction(Habitacion habitacion) {
        
        Cliente cliente = FindorcreateCliente ();

        Date Fechainicio = Dateinicio.getDate();
        Date Fechafin = Datefin.getDate();
        
        long time = Fechafin.getTime() - Fechainicio.getTime();
        int dias = (int)(time / 1000 / 60 / 60 / 24);
        

        if (ComboboxTipopago.getItemCount() == 0) {
            for (TipoPago tipopago : TipoPago.values()) {
                ComboboxTipopago.addItem(tipopago.name());
            }

            ComboboxTipopago.addItemListener((e) -> {
                selectedTipopago = TipoPago.valueOf(ComboboxTipopago.getSelectedItem().toString());
            });
        }
        double total = dias * habitacion.getPrecioPorNoche();
        Totallabel.setText("Total: $ " + total);

        Reservacion reservacion = new Reservacion(Fechainicio, Fechafin, habitacion, cliente, total, selectedTipopago);

    }

    private Cliente FindorcreateCliente() {

        String Email = EmailDatosPersonales.getText();
        String Documento = DocumentoDatosPersonales.getText();

        Cliente clienteReservacion = null;

        for (Cliente cliente : Main.clientes()) {
            if (cliente.getEmail().equals(Email) && cliente.getDocumento().equals(Documento)) {
                clienteReservacion = cliente;
            }
        }
        if (clienteReservacion == null) {
            clienteReservacion = new Cliente(Documento, NombreDatosPersonales.getText(), Email);
            Main.hotel.getClientes().crear(clienteReservacion);
        }
        return clienteReservacion;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboboxTipopago;
    private com.toedter.calendar.JDateChooser Datefin;
    private com.toedter.calendar.JDateChooser Dateinicio;
    private javax.swing.JPanel DatosReservacontent;
    private javax.swing.JTextField DocumentoDatosPersonales;
    private javax.swing.JLabel Documentolabel;
    private javax.swing.JTextField EmailDatosPersonales;
    private javax.swing.JLabel Emaillabel;
    private javax.swing.JTextField NombreDatosPersonales;
    private javax.swing.JLabel Nombrelabel;
    private javax.swing.JLabel Totallabel;
    private javax.swing.JPanel contentReserva;
    private javax.swing.JPanel datosClientereservacontent;
    private javax.swing.JPanel datosPagoreservacontent;
    private javax.swing.JLabel findelareservalabel;
    private javax.swing.JLabel iniciodelareservalabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelDatosPersonales;
    private javax.swing.JLabel labelDatosReserva;
    private javax.swing.JLabel labelDatosReserva1;
    private javax.swing.JButton realizarReservacion;
    private javax.swing.JPanel reservacontent;
    private javax.swing.JLabel tipoPagolabel;
    private javax.swing.JPanel visualHabitacionReservar;
    // End of variables declaration//GEN-END:variables
}
